# Generated by Django 5.0 on 2023-12-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
