# Generated by Django 5.0 on 2023-12-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0003_movieinfo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='img',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='poster',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
