# Generated by Django 5.0 on 2023-12-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0004_remove_movieinfo_img_movieinfo_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='poster',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
